### PR TITLE
email autocomplete feature

### PR DESCRIPTION
**Pull request by kucherenkovova**

### CODE REVIEW

**Comment by hugohil** [comment]
Thank you !
Could you keep the minified file in the dist folder please ?

Also, why'd you write `[{name: 'email', value: '@gmail.com'}]` and not just `['@gmail.com']` ? I don't see any special rule in the `piano.js` file for this type of input.

**Comment by kucherenkovova** [comment]
> Could you keep the minified file in the dist folder please ?
Do you mean that I shouldn't push the minified one?
> Also, why'd you write [{name: 'email', value: '@gmail.com'}] and not just ['@gmail.com'] ?
piano is adding a custom class 'email' to li element on line 114. I added this style to css

**Comment by hugohil** [comment]
Ok, my bad for the 'email' thing ;)
Yep, just push the minified files again and I'll merge

**Comment by hugohil** [comment]
Oops, my bad, You've just add the new ones ! Forget it.

**Pull request merged**
